### ISSUE TITLE
Tuple sorting

### ISSUE THREAD

**Issue by gdalle** [nmorale5/NoahYixiaoHashCode.jl#10]
https://github.com/nmorale5/NoahYixiaoHashCode.jl/blob/449e3d8b75060206bb4a287c18d7621f811e54b2/src/solver_greedy.jl#L6

By default, Julia seems to sort tuples in the way you'd expect:

```julia
julia> (1, 2) < (4, 0)
true

julia> (1, 2) < (1, 0)
false
```

**Comment by Yixiao-Zhang** [comment]
I get it.
