### ISSUE TITLE
Your package can depend on HashCode2014.jl

### ISSUE THREAD

**Issue by gdalle** [nmorale5/NoahYixiaoHashCode.jl#7]
https://github.com/nmorale5/NoahYixiaoHashCode.jl/blob/449e3d8b75060206bb4a287c18d7621f811e54b2/src/NoahYixiaoHashCode.jl#L2
I see that you did a good job copying and adapting data structures from HashCode2014.jl, but you didn't have to: the easy way is to make it a dependency and redefine only what you need to. In particular, this will save you trouble when it comes to reading and writing txt files

**Comment by gdalle** [comment]
However I'm reading your code and seeing that your structures are very clean and in some cases better than mine, so I'm ruling that you don't _have_ to depend on HashCode2014.jl, you just _can_ if you want to!

**Comment by gdalle** [comment]
https://github.com/nmorale5/NoahYixiaoHashCode.jl/blob/449e3d8b75060206bb4a287c18d7621f811e54b2/src/routing_problem.jl#L49

This is one of the reasons why depending on my code would be easier and avoid duplicates. For instance, you could create a `City` object with my functions, and then add the `sid_matrix` to make it a `RoutingProblem`. Besides, it makes your package more robust in case, say, the input format changes and HashCode2014.jl evolves. But again, you did nothing wrong.

**Comment by Yixiao-Zhang** [comment]
You are right. Initially, I though it would be easier to write `load_problem` myself than looking into someone else's code. Another reason is the problems caused by third-party libraries, like dependency conflicts and API changes. In this case, I will just leave the code as it is, since it is correct.
