### ISSUE TITLE
Specify the nature of `sid_matrix`

### ISSUE THREAD

**Issue by gdalle** [nmorale5/NoahYixiaoHashCode.jl#8]
https://github.com/nmorale5/NoahYixiaoHashCode.jl/blob/449e3d8b75060206bb4a287c18d7621f811e54b2/src/routing_problem.jl#L14

Some of your code will error if `sid_matrix` is anything else than a sparse matrix. You can specify it either in the docs or as a type constraint (the former being more "Julian" to allow for other uses of your struct)

**Comment by Yixiao-Zhang** [comment]
I have specified that in the docs.
