### ISSUE TITLE
Why do you need this to be `<:Number`?

### ISSUE THREAD

**Issue by gdalle** [nmorale5/NoahYixiaoHashCode.jl#9]
https://github.com/nmorale5/NoahYixiaoHashCode.jl/blob/449e3d8b75060206bb4a287c18d7621f811e54b2/src/solver_greedy.jl#L1

**Comment by Yixiao-Zhang** [comment]
I think that a heuristic should return a number. But in the latest version of code, I just use integer as the return value, and this structure is removed.
